### ISSUE TITLE
Think it fails on this testcase

### ISSUE THREAD

**Issue by aaron-michaux** [jamespayor/weighted-bipartite-perfect-matching#2]
```
Hungarian produced:
*8463   4191   3132   0000   0000
 6852   5245  *2044   0000   0000
 4434   8781   2295  *0000   0000
 0273   5344   6704   0000  *0000
 9139  *4173   4572   0000   0000


Actual solution:
 8463   4191   3132  *0000   0000
 6852   5245  *2044   0000   0000
 4434   8781   2295   0000  *0000
*0273   5344   6704   0000   0000
 9139  *4173   4572   0000   0000
```

**Comment by jamespayor** [comment]
I tried running your case (see the above commit). I get the correct matching output.
Do you have more information about how you're running it? You may well be hitting an issue in the algorithm, though it seems like a pipeline problem to me given that it solves the case when I try it.
(Closing for now.)

**Comment by aaron-michaux** [comment]
Hi, I'm sorry that it's too long ago. I had the code and test all set up a month ago, I've long since moved on. Maybe I made a mistake. Regardless, I ended up writing my own algorithm, using modern C++ style.

**Comment by jamespayor** [comment]
Cool; thanks for the note
